source 'https://rubygems.org'

gem "jekyll", "~> 3.9.2"
gem 'jekyll-compose', group: [:jekyll_plugins]
gem "github-pages", "~> 226"
gem "rake", "~> 12.3.0"
gem 'jekyll-paginate'
gem "webrick", "~> 1.7"
